version: '3'
services:
  movies-front:
    build:
      context: ./movies-front/
      dockerfile: Dockerfile
    ports:
      - ${REACT_PORT}:${REACT_PORT}
    environment:
      - REACT_PORT
      - REACT_APP_API_URI
      # completa esta seccion, lee el archivo README en la carpeta movies-front 
    volumes:
      - ./movies-front:/usr/app
      - /usr/app/node_modules
    depends_on:
      - movies-api
    # de que servicio depende el frontend?   
    command: npm start

  movies-api:
    build:
      context: ./movies-api/
      target: build-release-stage
      dockerfile: Dockerfile
    environment:
      - BIND_IP
      - BIND_PORT
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_SERVER
      - POSTGRES_PORT
    # completa esta seccion, lee el archivo README en la carpeta movies-api
    command: /movies-api -b ${BIND_IP} -p ${BIND_PORT} ; go test
    expose:
      - ${POSTGRES_PORT}
    depends_on:
      - postgres
    restart: always
    ports:
      - ${BIND_PORT}:${BIND_PORT}
  postgres:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_PORT
    expose:
      - ${POSTGRES_PORT}

  flyway:
    image: flyway/flyway:latest
    container_name: migration_flyway2
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://${POSTGRES_SERVER}:${POSTGRES_PORT}/${POSTGRES_DB}
      - FLYWAY_GROUP=true
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./sql_migrations:/flyway/sql
    depends_on:
      - postgres
